version: 2
references:
  test: &test
    run:
      name: Run tests
      command: |
        echo "bundle exec $(circleci tests split .circleci/spec-cmds)"
        bundle exec $(circleci tests split .circleci/spec-cmds)
  build_lock: &build_lock
    run:
      name: Build Gemfile.lock file
      command: bundle lock
  restore: &restore
    restore_cache:
      keys:
        - v2-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-
  bundle: &bundle
    run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
        bundle exec appraisal install
  save: &save
    save_cache:
      paths:
        - ./vendor/bundle
        - ./gemfiles/vendor/bundle
      key: v2-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  "ruby-2.4":
    docker:
      - image: circleci/ruby:2.4
    parallelism: 3
    steps:
      - checkout
      - <<: *build_lock
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *test
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    parallelism: 3
    steps:
      - checkout
      - <<: *build_lock
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *test
  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6
    parallelism: 3
    steps:
      - checkout
      - <<: *build_lock
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *test
  "jruby":
    docker:
      - image: circleci/jruby:9.2.7-jdk
        environment:
          BUNDLER_VERSION: 1.17.3
          JRUBY_OPTS: "--dev"
    parallelism: 3
    steps:
      - checkout
      - <<: *build_lock
      - <<: *restore
      - <<: *bundle
      - <<: *save
      - <<: *test

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.4"
      - "ruby-2.5"
      - "ruby-2.6"
      - "jruby"
